tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "surface-bright": "#f9f9ff",
                    "background": "#f9f9ff",
                    "on-tertiary-fixed": "#191c1d",
                    "on-surface": "#111c2c",
                    "secondary-fixed-dim": "#e9c176",
                    "outline": "#75777e",
                    "surface-container-lowest": "#ffffff",
                    "primary-fixed-dim": "#b9c7e4",
                    "surface-variant": "#d8e3fa",
                    "surface-dim": "#cfdaf1",
                    "surface-container-high": "#dee8ff",
                    "inverse-surface": "#263142",
                    "on-surface-variant": "#44474d",
                    "outline-variant": "#c5c6cd",
                    "inverse-on-surface": "#ebf1ff",
                    "surface": "#f9f9ff",
                    "secondary-container": "#fed488",
                    "on-error": "#ffffff",
                    "tertiary-fixed": "#e1e3e4",
                    "on-secondary": "#ffffff",
                    "primary": "#000000",
                    "on-secondary-fixed-variant": "#5d4201",
                    "error-container": "#ffdad6",
                    "on-tertiary": "#ffffff",
                    "on-secondary-container": "#785a1a",
                    "inverse-primary": "#b9c7e4",
                    "on-primary": "#ffffff",
                    "surface-container-highest": "#d8e3fa",
                    "tertiary": "#000000",
                    "on-tertiary-container": "#828485",
                    "surface-container-low": "#f0f3ff",
                    "primary-fixed": "#d6e3ff",
                    "on-primary-fixed-variant": "#39475f",
                    "secondary": "#775a19",
                    "on-secondary-fixed": "#261900",
                    "on-tertiary-fixed-variant": "#454748",
                    "on-primary-fixed": "#0d1c32",
                    "tertiary-container": "#191c1d",
                    "secondary-fixed": "#ffdea5",
                    "surface-tint": "#515f78",
                    "tertiary-fixed-dim": "#c5c7c8",
                    "on-primary-container": "#76849f",
                    "on-error-container": "#93000a",
                    "primary-container": "#0d1c32",
                    "surface-container": "#e7eeff",
                    "error": "#ba1a1a",
                    "on-background": "#111c2c"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "spacing": {
                    "stack-lg": "64px",
                    "stack-sm": "16px",
                    "margin-desktop": "80px",
                    "gutter": "32px",
                    "max-container": "1440px",
                    "section-padding": "120px",
                    "stack-md": "32px"
            },
            "fontFamily": {
                    "body-lg": ["Montserrat"],
                    "body-md": ["Montserrat"],
                    "headline-lg": ["Montserrat"],
                    "headline-md": ["Montserrat"],
                    "label-lg": ["Montserrat"],
                    "label-md": ["Montserrat"],
                    "display-lg": ["Montserrat"]
            },
            "fontSize": {
                    "body-lg": ["18px", {"lineHeight": "32px", "fontWeight": "400"}],
                    "body-md": ["16px", {"lineHeight": "28px", "fontWeight": "400"}],
                    "headline-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                    "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                    "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1em", "fontWeight": "600"}],
                    "label-md": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
                    "display-lg": ["72px", {"lineHeight": "84px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
            }
          },
        },
      }